version: '1'

services:
  next-frontend:
    build: ./app/next-frontend
    container_name: next_frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
      - ./app/next-frontend:/app
    depends_on:
      - nest-backend
  
  nest-backend:
    build: ./app/nest-backend
    container_name: nest_backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://user:postgres@db:5432/postgres
    volumes:
      - ./app/nest-backend:/app
    depends_on:
      - db

  db:
    build: ./postgres-db
    container_name: postgres_pta
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
      image: dpage/pgadmin4:8.4
      ports:
        - 8000:80
      volumes:
        - pgadmin-data:/var/lib/pgadmin
        - ./config/servers.json:/pgadmin4/servers.json
      environment:
        PGADMIN_DEFAULT_EMAIL: user@example.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      depends_on:
        - db 

volumes:
  db-data:
  pgadmin-data: